spring:
  application:
    name: finance-backend

  datasource:
    url: jdbc:postgresql://dpg-d79sljnkijhs73938k10-a:5432/finance_db_p8wh
    username: finance_db_p8wh_user
    password: Z0izF8YqEvsdvILSpG469pwOi87TRHa1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

  sql:
    init:
      mode: always

server:
  port: 8080

app:
  jwt:
    secret: bXlTdXBlclNlY3JldEtleUZvckp3dFRva2VuU2lnbmluZzEyMzQ1Njc4OTA=
    expiration-ms: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
